In [1]:
import numpy as np

In [2]:
ar=np.array([2,3,4,6])

In [3]:
ar

array([2, 3, 4, 6])

In [4]:
x=ar+10

In [5]:
x

array([12, 13, 14, 16])

In [6]:
ar.shape 

(4,)

In [7]:
ar.dtype

dtype('int32')

In [8]:
arr=np.array([2.0,5.3,6.0])

In [9]:
arr.dtype

dtype('float64')

#TWO DIMENSION

In [10]:
a=np.array([(2,5,6),
         (6,4,5)])

In [11]:
a

array([[2, 5, 6],
       [6, 4, 5]])

In [12]:
a.size

6

In [13]:
a.shape 

(2, 3)

In [14]:
b=np.array([(1,2,3),
    (4,5,6),
    (7,8,9)])

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
b.shape

(3, 3)

In [17]:
c=np.array([(2,4,5,6),
           (7,8,9,0),
           (2,5,3,4)])

In [18]:
c

array([[2, 4, 5, 6],
       [7, 8, 9, 0],
       [2, 5, 3, 4]])

In [19]:
c.shape

(3, 4)

In [20]:
d=np.zeros((2,2),dtype=np.int16)

In [21]:
d

array([[0, 0],
       [0, 0]], dtype=int16)

In [22]:
e=np.ones((3,2),dtype=np.int16)

In [23]:
e

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [24]:
f = np.array([(1,2,3), (4,5,6)])

In [25]:
f

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
f.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
f.flatten()

array([1, 2, 3, 4, 5, 6])

In [28]:
h=np.array([2,3,4])
g=np.array([5,6,7])

In [29]:
np.hstack((h,g))

array([2, 3, 4, 5, 6, 7])

In [30]:
np.vstack((h,g))

array([[2, 3, 4],
       [5, 6, 7]])

In [31]:
np.random.normal(5,10,11)

array([  5.05012415,   5.14260961, -10.44855475,  10.80656256,
         2.81568677,  22.8982494 , -26.9592754 ,  10.7921145 ,
        -3.60140002,  -0.73280519,  18.30386617])

In [32]:
j=np.matrix(np.zeros((5,5),dtype=np.int16))

In [33]:
j

matrix([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=int16)

In [34]:
k=np.matrix(np.ones((3,3),dtype=np.int16))

In [35]:
k

matrix([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=int16)

In [36]:
np.asarray(k)[2]=2

In [37]:
k

matrix([[1, 1, 1],
        [1, 1, 1],
        [2, 2, 2]], dtype=int16)

In [38]:
np.arange(1,40)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [39]:
np.arange(1,50,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [40]:
np.linspace(2, 14, num=10)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        , 11.33333333, 12.66666667, 14.        ])

In [41]:
np.logspace(2, 30, num=2)

array([1.e+02, 1.e+30])

In [42]:
l=np.array([(1,2,3),(4,7,3)])

In [43]:
l

array([[1, 2, 3],
       [4, 7, 3]])

In [44]:
l[0]

array([1, 2, 3])

In [45]:
l[1]

array([4, 7, 3])

In [46]:
l[:,1]

array([2, 7])

In [47]:
l[1,0]

4

In [48]:
l[:,2]

array([3, 3])

In [49]:
l[:1,2]

array([3])

In [50]:
m=np.random.normal([2,10,20])

In [51]:
m

array([ 2.75405418,  8.66559105, 19.93304335])

In [52]:
n=np.array([1,2,3,4,5])

In [53]:
np.max(n)

5

In [54]:
np.min(n)

1

In [55]:
np.mean(n)

3.0

In [56]:
np.median(n)

3.0

In [57]:
np.std(n)

1.4142135623730951

In [58]:
q=np.array([2,3,4])
w=np.array([1,2,3])

In [59]:
np.dot(q,w)

20

In [60]:
o=np.array([[2,3],[2,3]])
p=np.array([[5,4],[4,1]])

In [61]:
np.matmul(o,p)

array([[22, 11],
       [22, 11]])

In [62]:
z=np.array([[1,2,3],
           [5,3,2],
           [1,5,4]])

In [63]:
print(np.linalg.inv(z))

[[ 0.0625   0.21875 -0.15625]
 [-0.5625   0.03125  0.40625]
 [ 0.6875  -0.09375 -0.21875]]


In [64]:
y=np.array([[1,2],[1,4]])

In [65]:
det = np.linalg.det(y)

In [66]:
det

2.0

In [67]:
x=np.array([[11,3,1,0],
           [-4,0,1,6],
           [0,1,1,1],
           [2,6,1,9]])

In [68]:
np.linalg.matrix_rank(x)

4

In [69]:
a=np.array([[1,6,1],
           [1,2,0],
           [0,0,3]])

In [70]:
eigenvalues, eigenvectors = np.linalg.eig(a)

In [71]:
eigenvalues,eigenvectors

(array([-1.,  4.,  3.]),
 array([[-0.9486833 , -0.89442719, -0.23570226],
        [ 0.31622777, -0.4472136 , -0.23570226],
        [ 0.        ,  0.        ,  0.94280904]]))

In [72]:
g = np.matrix('[2,4; 5,6]')

In [73]:
g

matrix([[2, 4],
        [5, 6]])

In [74]:
diag = g.diagonal()

In [75]:
diag

matrix([[2, 6]])

In [76]:
trans = g.transpose()

In [77]:
trans

matrix([[2, 5],
        [4, 6]])

In [78]:
trace = g.trace()

In [79]:
trace

matrix([[8]])